# Site settings
title: A Conta dos Passaralhos
tag_text: A Conta dos Passaralhos
description: Um panorama sobre demissões de jornalistas nas redações do Brasil desde 2012.
jornalistas: 1887
total: 6147
atualizacao: 20/07/2017

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
